### PR TITLE
added missing saml: namespace to AttributeStatement

### PR DESCRIPTION
**Pull request by bschelling**
instead of '<saml:AttributeStatement>'  only  an '<AttributeStatement>' tag is generated. looks like ab bug to me :)

### CODE REVIEW

**Comment by mcastany** [comment]
@bschelling  - Can you include a test for this change ?

**Comment by bschelling** [comment]
yes, but will need some time, swamped with work. error should be obvious.

**Comment by mcastany** [comment]
You can do something like this (in `saml20.tests.js`). I don't want to merge it without tests because if we don't include them, nothing prevents us from breaking this again.

```
  it('should include attribute statement with the correct prefix', function () {
     var options = {
      cert: fs.readFileSync(__dirname + '/test-auth0.pem'),
      key: fs.readFileSync(__dirname + '/test-auth0.key'),
      xpathToNodeBeforeSignature: "//*[local-name(.)='Conditions']",
      attributes: {
        'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress': 'foo@bar.com',
        'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name': 'Foo Bar'
      }
    };

    var signedAssertion = saml.create(options);
    
    var isValid = utils.isValidSignature(signedAssertion, options.cert);
    assert.equal(true, isValid);
    var doc = new xmldom.DOMParser().parseFromString(signedAssertion);
    var attributeStatement = doc.documentElement.getElementsByTagName('saml:AttributeStatement');
    assert.equal(attributeStatement.length, 1);
  });
```

**Comment by bschelling** [comment]
I added a simple test - hope that works, lmk

**Comment by mcastany** [comment]
v0.12.3 published

**Pull request merged**
